# Generated by Django 5.2.6 on 2025-09-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_learningitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('On_Going', 'On Going')], default='Pending', max_length=20),
        ),
    ]
