# Generated by Django 5.2.6 on 2025-09-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_learningitem_user_subject_user_alter_task_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('On Going', 'On Going')], default='Pending', max_length=20),
        ),
    ]
