# Generated by Django 6.0.3 on 2026-04-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0009_alter_subject_name_alter_subject_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminder_4_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_7_sent',
            field=models.BooleanField(default=False),
        ),
    ]
